version: '3.8'

services:
  postgres:
    container_name: nestjs-redis-example-postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data

  redis:
    container_name: nestjs-redis-example-redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'

volumes:
  postgres:
    driver: local